#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > btbbtest.c
#include <btbb.h>

int main()
{
    return 0;
}
EOF

pkg-config --cflags --libs libbtbb

gcc -o btbbtest btbbtest.c `pkg-config --cflags --libs libbtbb`
echo "build: OK"
[ -x btbbtest ]
# > /dev/null because it writes this: full talloc report on 'sccp' (total      1 bytes in   1 blocks)
./btbbtest
echo "run: OK"

